social_network/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

social_network/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/delete/', views.delete_post, name='post_delete'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('posts/<int:post_id>/comment/<int:comment_id>/delete/',
         views.delete_comment, name='delete_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
]

social_network/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

social_network/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from core.models import CreatedModel


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Имя')
    slug = models.SlugField(max_length=50, unique=True, verbose_name='Адрес')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField('Текст поста', help_text='Введите текст поста')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='posts',
                               verbose_name='Автор')
    group = models.ForeignKey(Group,
                              on_delete=models.SET_NULL,
                              blank=True,
                              null=True,
                              related_name='posts',
                              verbose_name='Группа',
                              help_text='Выберете группу')
    image = models.ImageField('Картинка', upload_to='posts/', blank=True)

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        LEN_OF_POST = 15
        return self.text[:LEN_OF_POST]


class Comment(CreatedModel):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments',
                             verbose_name='Текст поста',
                             blank=True,
                             null=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments',
                               verbose_name='Автор')
    text = models.TextField('Комментарий', help_text='Напишите комментарий')

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(User, related_name='follower',
                             on_delete=models.CASCADE)
    author = models.ForeignKey(User, related_name='following',
                               on_delete=models.CASCADE)

    class Meta:
        ordering = ('-author',)
        verbose_name = 'Лента автора'
        verbose_name_plural = 'Лента авторов'
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'], name='unique_members')]

social_network/posts/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

    def clean_text(self):
        '''Самая примитивная реализация отбора'''
        old_comment = self.cleaned_data['text']
        comment = self.cleaned_data['text']
        regulation = ['Пушкин', 'Толстой']
        for element in range(len(regulation)):
            regulation[element] = regulation[element].upper()
        regulation = set(regulation)
        comment = comment.upper()
        comment = set(comment.split(' '))
        if comment.intersection(regulation):
            raise ValidationError("Forbidden word!")
        return old_comment

social_network/posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from .models import Post, Group, Comment, Follow
from .forms import PostForm, CommentForm

LAST_POSTS = 10


def paginator_group(request, post_list):
    paginator = Paginator(post_list, LAST_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.select_related('author', 'group').all()
    page_obj = paginator_group(request, post_list)
    return render(request, template, {'page_obj': page_obj})


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author').all()
    page_obj = paginator_group(request, post_list)
    context = {'group': group,
               'page_obj': page_obj}
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('group').all()
    page_obj = paginator_group(request, post_list)
    following = (request.user.is_authenticated
                 and Follow.objects.filter(user=request.user,
                                           author=author).exists())
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def delete_comment(request, comment_id, post_id):
    comment = get_object_or_404(Comment, id=comment_id)
    post = get_object_or_404(Post, id=post_id)
    if comment.author == request.user:
        comment.delete()
    return redirect('posts:post_detail', post.id)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', request.user)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    author = post.author
    if author != request.user:
        return redirect('posts:post_detail', post_id)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author == request.user:
        post.delete()
    return redirect('posts:profile', request.user)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    posts_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator_group(request, posts_list)
    context = {"page_obj": page_obj}
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    user = request.user
    Follow.objects.filter(user=user, author__username=username).delete()
    return redirect("posts:profile", username=username)

social_network/templates/posts/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <div class="container">
        <h5 class="mt-0">
          <a href="{% url 'posts:profile' comment.author.username %}">
            {{ comment.author.get_full_name }}
          </a>
        </h5>
        <li class="list-group-item">
          {{ comment.text }}
          <div class="text-end">
            {% if comment.author == user %}
              <form action="{% url 'posts:delete_comment' post.id comment.id %}" method="post">
              {% csrf_token %}
                <button type="submit" class="btn btn-sm btn-danger">Удалить</button>
              </form>
            {% endif %}
          </div>
        </li>
      </div>
    </div>
  </div>
{% endfor %}

social_network/templates/posts/create_post.html
{% extends "base.html" %}

{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Добавить пост
  {% endif %}
{% endblock %}

{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            {% if is_edit %}
              <form method="post" action="{% url 'posts:post_edit' post.id %}" enctype="multipart/form-data">
            {% else %}
              <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
            {% endif %}
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row" aria-required=
                      {% if field.field.required %}
                        "true"
                      {% else %}
                        "false"
                      {% endif %}>
                <label for="{{ field.id_for_label }}"
                       class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required">*</span>
                  {% endif %}
                </label>
              <div class="col-md-6">{{ field|addclass:"form-control" }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help"
                         class="form-text text-muted">{{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

social_network/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Лента автора{% endblock %}
{% block content %}
  <div class="container py-4">
    {% include 'includes/swither.html' with follow=True %}
    {% for post in page_obj %}
      {% include 'posts/posts_list.html' with profile_link_flag=True author_link=True %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock content %}

social_network/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Здесь будет информация о группах проекта Yatube
{% endblock %}

{% block content %}
  <div class="container py-4">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      {% include 'posts/posts_list.html' with profile_link_flag=True author_link=True %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

social_network/templates/posts/index.html
{% extends "base.html" %}
{% load cache %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
  <div class="container py-4">
    {% include 'includes/swither.html' with index=True follow=False %}
    {% cache 20 index_page page_obj %}
      {% for post in page_obj %}
        {% include 'posts/posts_list.html' with profile_link_flag=True author_link=True %}
      {% endfor %}
      {% include 'includes/paginator.html' %}
    {% endcache %}
  </div>
{% endblock %}

social_network/templates/posts/post_detail.html
{% extends "base.html" %}

{% block title %}
  Страница поста {{ post|truncatechars:30 }}
{% endblock %}

{% load thumbnail %}

{% block content %}
  <div class="container py-4">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group }}
            <a href="{% url "posts:group_list" post.group.slug %}">
              все записи группы
            </a>
          </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post.author.posts.count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url "posts:profile" post.author.username %}">
              Все посты пользователя
            </a>
          </li>
          {% if post.author == user %}
            <li class="list-group-item">
              <a href="{% url "posts:post_edit" post.id %}">
                Редактировать пост
              </a>
            </li>
            <li class="list-group-item">
              <a href="{% url "posts:post_delete" post.id %}">
                Удалить пост
              </a>
            </li>
          {% endif %}
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaks }}
        </p>
        <div class="card my-4">
          {% include 'posts/comments.html' %}
        </div>
      </article>
    </div>
  </div>
{% endblock %}

social_network/templates/posts/posts_list.html
{% load thumbnail %}
<article>
  <ul>
    {% if author_link %}
      <li>
        Автор: {{ post.author.username }}
        <a href="{% url 'posts:profile' post.author.username %}">
          все посты пользователя
        </a>
      </li>
    {% endif %}
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}     
  <p>{{ post.text }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
  {% if post.group %}
    {% if profile_link_flag %}
      <p><a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group }}</a></p>
    {% endif %}
  {% endif %}    
</article>
{% if not forloop.last %}<hr>{% endif %} 

social_network/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
  <div class="container py-4">
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    <h6>Число подписчиков: {{ author.following.count }}</h6>
    <h6>Подписан на количество авторов: {{ author.follower.count }}</h6>
    {% if author != request.user %}
      {% if following %}
        <a class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button">
          Отписаться
        </a>
      {% else %}
        <a class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button">
          Подписаться
        </a>
      {% endif %}
    {% endif %}
  </div>
  {% for post in page_obj %}
    {% include 'posts/posts_list.html' with profile_link_flag=True author_link=False%}
  {% endfor %}
  {% include 'includes/paginator.html' %}
  </div>
{% endblock content %}